language: cpp

dist: trusty
sudo: required

branches:
  only:
    - master
    - develop
    - feature/boost_removal
compiler:
  - gcc

os:
  - linux  
  - osx

before_install:

  # G++ 8 compiler, OpenCV dependencies, dlib, openblas, and tbb
  - if [ ${TRAVIS_OS_NAME} = linux ]; then  
      sudo apt-get update;
      sudo apt-get upgrade;
      sudo apt-get dist-upgrade;
      sudo apt-get install libopenblas-dev;
      sudo apt-get install build-essential software-properties-common -y;
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -y;
      sudo apt-get install gcc-8 g++-8 -y;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8;
      sudo update-alternatives --config gcc
      select gcc-8
      sudo apt-get install git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev;
      sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev;
      sudo apt-get install cmake;
      wget http://dlib.net/files/dlib-19.13.tar.bz2;
      tar xf dlib-19.13.tar.bz2;
      cd dlib-19.13;
      mkdir build;
      cd build;
      cmake ..;
      cmake --build . --config Release;
      sudo make install;
      sudo ldconfig;
      cd ../..;
      wget https://github.com/opencv/opencv/archive/4.0.0.zip;
      unzip -qq 4.0.0.zip;
      cd opencv-4.0.0;
      mkdir build;
      cd build;
    fi

  # g++
  - if [ "$CXX" = "g++" ]; then
      if [ ${TRAVIS_OS_NAME} = linux ]; then
        $CXX --version;
        sudo cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_V4L=ON -D WITH_OPENCL=OFF -D INSTALL_C_EXAMPLES=OFF -D WITH_TBB=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF ..;
        sudo make -j4;
        sudo make install;
        cd ../..;
      fi 
    fi

  # clang
  - if [ "$CXX" = "clang++" ]; then
      if [ ${TRAVIS_OS_NAME} = linux ]; then  
        $CXX --version;
        sudo cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_V4L=ON -D WITH_OPENCL=OFF -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D WITH_TBB=ON ..;
        sudo make -j4;
        sudo make install;
        cd ../..;
      fi
    fi

  - if [ ${TRAVIS_OS_NAME} = osx ]; then  
      brew update;
      brew install tbb;
      brew install openblas;
      brew install dlib;
      brew install opencv3;
    fi
  
script:
  - $CXX --version
  - chmod 777 ./download_models.sh
  - ./download_models.sh
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_CXX_COMPILER=g++-8 .. 
  - make
  - ../build/bin/FeatureExtraction -f "../samples/2015-10-15-15-14.avi" -q -mloc model/main_clm_general.txt
  - ../build/bin/FaceLandmarkImg -fdir ../samples -out_dir data -multi_view 1 -wild -q
  - ../build/bin/FaceLandmarkImg -f ../samples/sample1.jpg -out_dir data -multi_view 1 -wild -q
  - ../build/bin/FeatureExtraction -fdir "../samples/image_sequence" -out_dir output -q
  - ../build/bin/FaceLandmarkVidMulti -fdir ../samples/image_sequence -q -mloc model/main_clm_general.txt
  - ../build/bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi -q -mloc model/main_clnf_general.txt